name: Coalitionify_api

on:
  push:
    branches:
      - main
    paths:
      - "demo.yaml"
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1   
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
            npm install --global yarn
            yarn install

    - name: Install Newman
      run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

    - name: Run Postman Collection
      run: |
        newman run Coalitionify-.postman_collection.json \
        --environment Coalitionify.postman_environment.json \
        --iteration-data data.json \
        --reporters cli,htmlextra \
        --reporter-htmlextra-export ./newman-report.html || echo "Test failed"
       
