name: Coalitionify_api

on:
  push:
    branches:
      - main
    paths:
      - "https://github.com/sumedhraj123/Postman/edit/main/demo.yaml"
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1  

workflow_dispatch:   

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
            npm install --global yarn
            yarn install

    - name: Install Newman
      run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

    - name: Run Postman Collection
      run: |
        newman run <https://github.com/sumedhraj123/Postman/edit/main/Coalitionify-.postman_collection.json> 
        -e <https://github.com/sumedhraj123/Postman/edit/main/Coalitionify.postman_environment.json> \
        -d <<https://github.com/sumedhraj123/Postman/edit/main/data.json> \
        -r htmlextra --reporter-htmlextra-export C:\Users\AYSUSER\Desktop\coalitionify-platform\index.html
      continue-on-error: true
       
